title: CNIT581 Robotics Project Spring 2018
description: > # this means to ignore newlines until "baseurl:"
  Project Blog for CNIT581 (SDR) Software Design and Development for Robotics by Mikaela Caron and Andrea Tidwell.
permalink: ':title/'
baseurl: "/CNIT581-Robotics-Project" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Mikaela Caron & Andrea Tidwell # add your name
author-img: authors.jpg # add your photo
about-author: We are seniors at Purdue University taking CNIT 581 Software Design and Development for Robotics.
  This blog is tracking our progress on our term project.

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
